### ISSUE TITLE
misc: JP updates

### ISSUE THREAD

**Issue by poppoerika** [momentohq/public-dev-docs#1128]
Note: make sure to match the titles and side bar labels with the translation for that page.

- [ ] translate the JP text in the top box  https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/introduction/common-caching-strategies.md 
- [ ] translate the JP text in the top box https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/develop/basics/datatypes.md
- [ ] translate `FAQ` and `Details`  https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/develop/basics/datatypes.md
Use `<summary>Method response object</summary>` to change the text in the `<detail>` tag 
- [ ] translate the JP text in the top box  https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/develop/basics/client-configuration-objects.md
- [ ] translate the JP text in the top box  https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/develop/basics/error-handling-production-readiness.md
- [ ] translate the JP text in the top box https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/develop/guides/working-with-files-cache.md
- [ ] translate the JP text in the top https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/develop/guides/working-with-time-series-data.md 
- [ ]  translate the JP text in the top  https://github.com/momentohq/public-dev-docs/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/cache/develop/api-reference/response-objects.md

**Comment by riokwmt** [comment]
#1137
