### ISSUE TITLE
Style: express string type consistently in API reference

### ISSUE THREAD

**Issue by malandis** [momentohq/public-dev-docs#124]
In the API reference, to refer to a `string`, sometimes we write `string` and other times `String`. I recommend we choose one and use it consistently.

**Comment by NoSQLKnowHow** [comment]
Which page are you looking at for this? I look in /develop/api-referece/ and in all of the tables it is "String". There are only 2 places on that page that have lowercase "string" and they are in paragraphs where they should be lowercase.

**Comment by malandis** [comment]
Looks like this was corrected since I reported. Nothing to do here. 👍
