### ISSUE TITLE
[JP Translation] Auth token -> API token

### ISSUE THREAD

**Issue by poppoerika** [momentohq/public-dev-docs#201]
https://github.com/momentohq/public-dev-docs/pull/200/files

**Comment by riywo** [comment]
@poppoerika The original commit was reverted: https://github.com/momentohq/public-dev-docs/pull/207 Should I wait for the follow up PR?

**Comment by NoSQLKnowHow** [comment]
Yes, please wait. More than likely, this will be canceled and thank you for asking!
