### ISSUE TITLE
Reference to missing Architecture Diagrams?

### ISSUE THREAD

**Issue by rohanmeh** [momentohq/public-dev-docs#273]
https://docs.momentohq.com/introduction/common-caching-patterns

"You can see why these caches get the name from the architecture diagrams below" but there's no architecture diagrams at the bottom of the page.

**Comment by poppoerika** [comment]
Add the attached aside/inline cache diagram after the below sentence:

> You can see why these caches get the name from the architecture diagrams below. The aside cache sits aside your application and is called separately from your data source. Alternatively, the inline cache is used inline with your request to the data source.

![image](https://github.com/user-attachments/assets/ea0cbf7e-15cc-47e9-a796-adcc8a7fc0ab)

**Comment by riokwmt** [comment]
https://github.com/momentohq/public-dev-docs/pull/1125
