### ISSUE TITLE
public dev docs: don't run translation in CI on PRs that come from a fork

### ISSUE THREAD

**Issue by cprice404** [momentohq/public-dev-docs#487]
if an OSS user files a docs PR from a fork, it fails CI because of the SIMPLEEN secret. We should make this step of the CI conditional and skip it on PRs that come from a fork so that users can submit docs changes w/o triggering a CI failure.

**Comment by nand4011** [comment]
![Image](https://github.com/momentohq/public-dev-docs/assets/747182/a9a141af-3668-4956-8e01-a3ec13b67a04)
