### ISSUE TITLE
Enable tabs for entire files that have been injected

### ISSUE THREAD

**Issue by pratik151192** [momentohq/public-dev-docs#506]
Our inject plugin works in two ways:

- Injecting snippets for different languages as Tabs for the same method name in different SDKs.
- OR, inject entire files by providing a path.

Currently we cannot inject entire files and also add a tabular view for different languages. Which is what the issue will aim to address

### Acceptance Criteria

- We should be able to inject entire files for different SDKs and support tab view.

**Comment by anitarua** [comment]
https://github.com/momentohq/public-dev-docs/pull/513
